name: Build PressTV APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Debug APK (app module)
        run: gradle :app:assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PressTV.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
